/**
 * DashyCore v7 — Share Hub source model.
 *
 * ONE canonical description of "the thing being shared", used by every
 * entry point (global nav, D-Code editor, project card, Studio asset).
 * Only source kinds that genuinely exist in this product are modelled.
 */

export type ShareSourceKind = "dcode-project" | "studio-asset" | "link";

/** A D-Code project. Its public URL is the real /d-code/share/<slug> page. */
export interface DCodeProjectSource {
  kind: "dcode-project";
  /** dcode_projects.id — ownership is always re-checked server-side (RLS). */
  id: string;
  title: string;
  language: string;
  fileCount: number;
  isPublic: boolean;
  shareSlug: string | null;
}

/** An image generated by the Pollinations engine and kept in the Studio library. */
export interface StudioAssetSource {
  kind: "studio-asset";
  id: string;
  prompt: string;
  imageUrl: string;
  createdAt: number;
}

/** Any other Dashy content the user wants to push out as text + link. */
export interface LinkSource {
  kind: "link";
  id: string;
  title: string;
  url: string;
}

export type ShareSource = DCodeProjectSource | StudioAssetSource | LinkSource;

export interface ResolvedSource {
  /** Human title shown in the SOURCE panel. */
  title: string;
  /** Short kind label, e.g. "D-Code project". */
  typeLabel: string;
  /** Public URL, when one genuinely exists right now. */
  url: string | null;
  /** Image URL when the source carries media. */
  mediaUrl: string | null;
  /** True when the source is currently reachable by anyone with the link. */
  isLive: boolean;
  /** Why there is no URL yet (shown as an actionable hint). */
  blockedReason: string | null;
}

export function sourceTypeLabel(kind: ShareSourceKind): string {
  switch (kind) {
    case "dcode-project":
      return "D-Code project";
    case "studio-asset":
      return "Studio asset";
    case "link":
      return "Dashy content";
  }
}

export function sourceKey(source: ShareSource): string {
  return `${source.kind}:${source.id}`;
}

/** Absolute origin for building public links (client-only). */
export function appOrigin(): string {
  if (typeof window === "undefined") return "";
  return window.location.origin;
}

export function resolveSource(source: ShareSource): ResolvedSource {
  switch (source.kind) {
    case "dcode-project": {
      const live = source.isPublic && !!source.shareSlug;
      return {
        title: source.title?.trim() || "Untitled project",
        typeLabel: sourceTypeLabel(source.kind),
        url: live ? `${appOrigin()}/d-code/share/${source.shareSlug}` : null,
        mediaUrl: null,
        isLive: live,
        blockedReason: live
          ? null
          : "This project is private. Create a public link to share it.",
      };
    }
    case "studio-asset":
      return {
        title: source.prompt.trim() || "Studio asset",
        typeLabel: sourceTypeLabel(source.kind),
        // The image itself lives on the generator's CDN and is publicly
        // reachable, so it doubles as the shareable URL.
        url: source.imageUrl,
        mediaUrl: source.imageUrl,
        isLive: true,
        blockedReason: null,
      };
    case "link": {
      const url = source.url.trim();
      return {
        title: source.title.trim() || url || "Untitled",
        typeLabel: sourceTypeLabel(source.kind),
        url: url || null,
        mediaUrl: null,
        isLive: !!url,
        blockedReason: url ? null : "Add a link to share.",
      };
    }
  }
}
